# Plugins TrueEC4D By SpringCraft, EditCraft, Demza
# TrueEC4D 3.0 (Yakiniku) Thanks for purchase
# If you have questions, you can ask at https://www.facebook.com/SpringCraftStudio

#Truewallet information settings
Email: "your@email.com"
Password: "Yakiniku16zz_"

